apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: spezistudyplatform-dev
      auth:
        workloadIdentity:
          clusterLocation: us-west1-a
          clusterName: spezistudyplatform-dev
          clusterProjectID: spezistudyplatform-dev
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
