apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: spezistudyplatform-prod
      auth:
        workloadIdentity:
          clusterLocation: us-west1
          clusterName: CLUSTER_NAME_TODO
          clusterProjectID: spezistudyplatform-prod
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
