apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - root-app.yaml
patches:
  - target:
      kind: Application
      name: traefik
    patch: |
      - op: replace
        path: /spec/sources/0/helm/valueFiles/0
        value: $values/argocd-apps/prod/traefik-values.yaml
  - target:
      kind: Application
      name: infrastructure
    patch: |
      - op: replace
        path: /spec/source/path
        value: infrastructure/prod
  - target:
      kind: Application
      name: apps
    patch: |
      - op: replace
        path: /spec/source/path
        value: apps/prod
  - target:
      kind: Application
      name: bootstrap
    patch: |
      - op: replace
        path: /spec/source/path
        value: bootstrap/prod
