apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli
  namespace: spezistudyplatform
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keycloak-config-cli
          env:
            - name: WEB_URL
              value: https://localhost
