apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-init-sql
  namespace: spezistudyplatform
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-init-sql
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        sql: "CREATE ROLE keycloak WITH LOGIN PASSWORD '{{ .password }}'; CREATE DATABASE keycloak OWNER keycloak;"
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-db-credentials
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
