#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spezistudyplatform-web
  namespace: spezistudyplatform
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: spezistudyplatform-web-container
          image: ghcr.io/stanfordspezi/spezistudyplatform-web:main
          resources:
            requests:
              memory: 64Mi
              cpu: 25m
            limits:
              memory: 256Mi
              cpu: 100m
