apiVersion: v1
kind: ConfigMap
metadata:
  name: spezistudyplatform-web-config
  namespace: spezistudyplatform
data:
  VITE_API_BASE_PATH: https://localhost
  VITE_KEYCLOAK_URL: https://localhost/auth
  VITE_KEYCLOAK_REALM: spezistudyplatform
  VITE_KEYCLOAK_CLIENT_ID: spezistudyplatform-web
