apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admin-secret-es.yaml
  - db-secret-es.yaml
  - keycloak.yaml
  - service-account.yaml
  - keycloak-config-cli-job.yaml
configMapGenerator:
  - name: keycloak-realm-config
    namespace: spezistudyplatform
    files:
      - 00-realm.json=realm/00-realm.json
generatorOptions:
  disableNameSuffixHash: true
