apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patches/server-deployment.yaml
  - path: patches/web-deployment.yaml
  - path: patches/server-configmap.yaml
  - path: patches/web-configmap.yaml
